apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ .Values.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      service: {{ .Values.name }}-website
  template:
    metadata:
      labels:
        service: {{ .Values.name }}-website
    spec:
      containers:
        - name: {{ .Values.name }}-website
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 60m
              memory: 256Mi
            requests:
              cpu: 30m
              memory: 128Mi
          ports:
            - containerPort: 80