apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      service: {{ .Release.Name }}-website
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}-website
    spec:
      containers:
        - name: {{ .Release.Name }}-website
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 60m
              memory: 256Mi
            requests:
              cpu: 30m
              memory: 128Mi
          ports:
            - containerPort: 80