apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-issuer'
  name: {{ .Values.name }}-ingress
  namespace: {{ .Values.name }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Values.name }}-service
                port:
                  number: 80
  tls:
    - hosts:
        - '{{ .Values.host }}'
      secretName: '{{ .Values.name }}-ingress-tls-secret'