apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.name }}
spec:
  selector:
    service: {{ .Values.name }}-website
  ports:
    - port: 80
      targetPort: 80