apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Name }}
spec:
  selector:
    service: {{ .Release.Name }}-website
  ports:
    - port: 80
      targetPort: 80